spring.application.name=RepoJuegos

spring.datasource.url=jdbc:mysql://localhost:3306/RepoJuegos?createDatabaseIfNotExist=true

spring.datasource.username=root

spring.datasource.password=IntoTheMACH1N3

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
